@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package nl.melonstudios.create.kinetics.contraption;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;